{{- if and .Values.server.persistence.enabled (not .Values.server.externalDatabase.enabled) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gerty.fullname" . }}-server-data
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "gerty.server.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.server.persistence.accessModes | nindent 4 }}
  {{- if .Values.server.persistence.storageClass }}
  storageClassName: {{ .Values.server.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.server.persistence.size }}
{{- end }}
