language: en-US
reviews:
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!docs/**"
    - "!*.md"
    - "!ml/dataset/raw/**"
    - "!ml/dataset/data/**"
    - "!test/fixtures/**"
    - "!deploy/grafana/**"
    - "!deploy/helm/k8s-sage/files/**"
  tools:
    semgrep:
      enabled: true
    golangci-lint:
      enabled: true
