sonar.organization=gregorytcarroll
sonar.projectKey=gregorytcarroll_k8s-sage
sonar.projectName=k8s-sage

sonar.sources=.
sonar.exclusions=**/vendor/**,**/*_test.go,test/**,ml/dataset/raw/**,ml/dataset/data/**,deploy/grafana/**,deploy/helm/k8s-sage/files/**

sonar.tests=.
sonar.test.inclusions=**/*_test.go,test/**

sonar.go.coverage.reportPaths=coverage.out

sonar.python.version=3.11
